### ISSUE TITLE
Write scenarios

### ISSUE THREAD

**Issue by GladkiyIvan** [FoxCaptainFox/QPoster#2]
Describe user scenarios with numbers & short clear sentences

**Comment by FoxCaptainFox** [comment]
1. Считать QR код.
2.1. Вызвать официанта.
2.2. Перейти на сайт заведения.
2.3. Сделать заказ.
2.3.1. Выбрать количество гостей.
2.3.2. Просмотреть меню.
2.3.3. Комментарий.
2.4.1. Просмотреть чек.
2.4.2. Оплатить чек.

**Comment by GladkiyIvan** [comment]
v.1 Scenarios 
[Scenarios.txt](https://github.com/FoxCaptainFox/QPoster/files/2478713/Scenarios.txt)
